[/Script/IOSRuntimeSettings.IOSRuntimeSettings]
;AudioSampleRate=48000
AudioMaxChannels=16
;AudioCallbackBufferFrameSize=1024
;AudioNumBuffersToEnqueue=2
;AudioNumSourceWorkers=0


[/Script/Engine.GarbageCollectionSettings]
gc.MaxObjectsInGame=1310720
gc.TimeBetweenPurgingPendingKillObjects=300.000000